// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://svadksfhpjqocthyrgtz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN2YWRrc2ZocGpxb2N0aHlyZ3R6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNTEwNjgsImV4cCI6MjA3MzkyNzA2OH0.5cgexx1T9GXLh1yUJdgTLrIYk4t6fxmkHFNDfV82Ynk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});